#!/usr/bin/env bash

# =========================================
#  TRENINGI Z BLOKU 10-TYGODNIOWEGO
#  Week 1–5, A i B (SZABLONY DO POPRAWY)
# =========================================

# ========== WEEK 1 – TRENING A ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-10-14T18:00:00Z",
    "template_name": "TRENING A – WEEK 1",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 1,
        "order_index": 1,
        "notes": "Back squat",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 75,  "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 90,  "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 90,  "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 90,  "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 2,
        "order_index": 2,
        "notes": "Bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 70, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 75, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 75, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 75, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 3,
        "order_index": 3,
        "notes": "Barbell row",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 3, "weight_kg": 65, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 65, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 65, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 4,
        "order_index": 4,
        "notes": "Pull-up (overhand, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 5,
        "order_index": 5,
        "notes": "Lateral raises",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 6,
        "order_index": 6,
        "notes": "Dips (parallel bars)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 7,
        "order_index": 7,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 8,
        "order_index": 8,
        "notes": "Triceps (pushdown/extension)",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 9,
        "order_index": 9,
        "notes": "Hip thrust",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 10,
        "order_index": 10,
        "notes": "Hollow hold (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 30, "is_warmup": false}
        ]
      },
      {
        "exercise": 11,
        "order_index": 11,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 1 – TRENING B ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-10-17T18:00:00Z",
    "template_name": "TRENING B – WEEK 1",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 12,
        "order_index": 1,
        "notes": "Deadlift (conventional)",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 80,  "reps": 2, "is_warmup": true},
          {"set_index": 5, "weight_kg": 90,  "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 90,  "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 90,  "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 13,
        "order_index": 2,
        "notes": "Overhead press (OHP)",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 30, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 40, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 50, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 50, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 50, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 50, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 14,
        "order_index": 3,
        "notes": "Chin-up (wąsko, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 15,
        "order_index": 4,
        "notes": "Close grip bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 5, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 6, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 16,
        "order_index": 5,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 17,
        "order_index": 6,
        "notes": "Plank (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 60, "is_warmup": false}
        ]
      },
      {
        "exercise": 18,
        "order_index": 7,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 2 – TRENING A ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-10-21T18:00:00Z",
    "template_name": "TRENING A – WEEK 2",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 1,
        "order_index": 1,
        "notes": "Back squat",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 75,  "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 92.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 2,
        "order_index": 2,
        "notes": "Bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 70, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 77.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 77.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 77.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 3,
        "order_index": 3,
        "notes": "Barbell row",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 3, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 70, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 4,
        "order_index": 4,
        "notes": "Pull-up (overhand, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 5,
        "order_index": 5,
        "notes": "Lateral raises",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 6,
        "order_index": 6,
        "notes": "Dips (parallel bars)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 7,
        "order_index": 7,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 8,
        "order_index": 8,
        "notes": "Triceps (pushdown/extension)",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 9,
        "order_index": 9,
        "notes": "Hip thrust",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 10,
        "order_index": 10,
        "notes": "Hollow hold (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 30, "is_warmup": false}
        ]
      },
      {
        "exercise": 11,
        "order_index": 11,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 2 – TRENING B ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-10-24T18:00:00Z",
    "template_name": "TRENING B – WEEK 2",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 12,
        "order_index": 1,
        "notes": "Deadlift (conventional)",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 80,  "reps": 2, "is_warmup": true},
          {"set_index": 5, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 100, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 13,
        "order_index": 2,
        "notes": "Overhead press (OHP)",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 30, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 40, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 50, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 52, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 52, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 52, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 14,
        "order_index": 3,
        "notes": "Chin-up (wąsko, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 15,
        "order_index": 4,
        "notes": "Close grip bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 5, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 6, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 16,
        "order_index": 5,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 17,
        "order_index": 6,
        "notes": "Plank (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 60, "is_warmup": false}
        ]
      },
      {
        "exercise": 18,
        "order_index": 7,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 3 – TRENING A ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-10-28T18:00:00Z",
    "template_name": "TRENING A – WEEK 3",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 1,
        "order_index": 1,
        "notes": "Back squat",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 75,  "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 92.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 2,
        "order_index": 2,
        "notes": "Bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 70, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 77.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 77.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 77.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 3,
        "order_index": 3,
        "notes": "Barbell row",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 3, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 70, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 4,
        "order_index": 4,
        "notes": "Pull-up (overhand, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 5,
        "order_index": 5,
        "notes": "Lateral raises",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 6,
        "order_index": 6,
        "notes": "Dips (parallel bars)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 7,
        "order_index": 7,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 8,
        "order_index": 8,
        "notes": "Triceps (pushdown/extension)",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 9,
        "order_index": 9,
        "notes": "Hip thrust",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 10,
        "order_index": 10,
        "notes": "Hollow hold (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 30, "is_warmup": false}
        ]
      },
      {
        "exercise": 11,
        "order_index": 11,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 3 – TRENING B ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-10-31T18:00:00Z",
    "template_name": "TRENING B – WEEK 3",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 12,
        "order_index": 1,
        "notes": "Deadlift (conventional)",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 80,  "reps": 2, "is_warmup": true},
          {"set_index": 5, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 100, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 13,
        "order_index": 2,
        "notes": "Overhead press (OHP)",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 30, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 40, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 50, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 52, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 52, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 52, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 14,
        "order_index": 3,
        "notes": "Chin-up (wąsko, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 15,
        "order_index": 4,
        "notes": "Close grip bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 5, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 6, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 16,
        "order_index": 5,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 17,
        "order_index": 6,
        "notes": "Plank (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 60, "is_warmup": false}
        ]
      },
      {
        "exercise": 18,
        "order_index": 7,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 4 – TRENING A ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-11-04T18:00:00Z",
    "template_name": "TRENING A – WEEK 4",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 1,
        "order_index": 1,
        "notes": "Back squat",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 75,  "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 92.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 2,
        "order_index": 2,
        "notes": "Bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 70, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 77.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 77.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 77.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 3,
        "order_index": 3,
        "notes": "Barbell row",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 3, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 70, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 4,
        "order_index": 4,
        "notes": "Pull-up (overhand, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 5,
        "order_index": 5,
        "notes": "Lateral raises",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 6,
        "order_index": 6,
        "notes": "Dips (parallel bars)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 7,
        "order_index": 7,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 8,
        "order_index": 8,
        "notes": "Triceps (pushdown/extension)",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 9,
        "order_index": 9,
        "notes": "Hip thrust",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 10,
        "order_index": 10,
        "notes": "Hollow hold (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 30, "is_warmup": false}
        ]
      },
      {
        "exercise": 11,
        "order_index": 11,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 4 – TRENING B ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-11-07T18:00:00Z",
    "template_name": "TRENING B – WEEK 4",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 12,
        "order_index": 1,
        "notes": "Deadlift (conventional)",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 80,  "reps": 2, "is_warmup": true},
          {"set_index": 5, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 100, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 13,
        "order_index": 2,
        "notes": "Overhead press (OHP)",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 30, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 40, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 50, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 52, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 52, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 52, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 14,
        "order_index": 3,
        "notes": "Chin-up (wąsko, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 15,
        "order_index": 4,
        "notes": "Close grip bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 5, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 6, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 16,
        "order_index": 5,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 17,
        "order_index": 6,
        "notes": "Plank (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 60, "is_warmup": false}
        ]
      },
      {
        "exercise": 18,
        "order_index": 7,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 5 – TRENING A ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-11-11T18:00:00Z",
    "template_name": "TRENING A – WEEK 5",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 1,
        "order_index": 1,
        "notes": "Back squat",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 75,  "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 92.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 92.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 2,
        "order_index": 2,
        "notes": "Bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 70, "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 80, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 80, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 80, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 3,
        "order_index": 3,
        "notes": "Barbell row",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 3, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 70, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 70, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 4,
        "order_index": 4,
        "notes": "Pull-up (overhand, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 5,
        "order_index": 5,
        "notes": "Lateral raises",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 6,
        "order_index": 6,
        "notes": "Dips (parallel bars)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 7,
        "order_index": 7,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 8,
        "order_index": 8,
        "notes": "Triceps (pushdown/extension)",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 9,
        "order_index": 9,
        "notes": "Hip thrust",
        "sets": [
          {"set_index": 1, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 10,
        "order_index": 10,
        "notes": "Hollow hold (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 30, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 30, "is_warmup": false}
        ]
      },
      {
        "exercise": 11,
        "order_index": 11,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'

# ========== WEEK 5 – TRENING B ==========
curl -X POST http://127.0.0.1:8000/api/workouts/ \
  -H "Content-Type: application/json" \
  -d '{
    "performed_at": "2025-11-14T18:00:00Z",
    "template_name": "TRENING B – WEEK 5",
    "notes": "Autogenerated template. Adjust to actual weights/sets.",
    "exercises": [
      {
        "exercise": 12,
        "order_index": 1,
        "notes": "Deadlift (conventional)",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 5, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 60,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 80,  "reps": 2, "is_warmup": true},
          {"set_index": 5, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 100, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 100, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 13,
        "order_index": 2,
        "notes": "Overhead press (OHP)",
        "sets": [
          {"set_index": 1, "weight_kg": 20,  "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 30,  "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 40,  "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 50,  "reps": 1, "is_warmup": true},
          {"set_index": 5, "weight_kg": 57.5, "reps": 5, "is_warmup": false},
          {"set_index": 6, "weight_kg": 57.5, "reps": 5, "is_warmup": false},
          {"set_index": 7, "weight_kg": 57.5, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 14,
        "order_index": 3,
        "notes": "Chin-up (wąsko, BW)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 4, "weight_kg": 0, "reps": 5, "is_warmup": false},
          {"set_index": 5, "weight_kg": 0, "reps": 5, "is_warmup": false}
        ]
      },
      {
        "exercise": 15,
        "order_index": 4,
        "notes": "Close grip bench press",
        "sets": [
          {"set_index": 1, "weight_kg": 20, "reps": 8, "is_warmup": true},
          {"set_index": 2, "weight_kg": 40, "reps": 5, "is_warmup": true},
          {"set_index": 3, "weight_kg": 55, "reps": 3, "is_warmup": true},
          {"set_index": 4, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 5, "weight_kg": 60, "reps": 8, "is_warmup": false},
          {"set_index": 6, "weight_kg": 60, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 16,
        "order_index": 5,
        "notes": "Biceps curls",
        "sets": [
          {"set_index": 1, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 10, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 10, "reps": 8, "is_warmup": false}
        ]
      },
      {
        "exercise": 17,
        "order_index": 6,
        "notes": "Plank (seconds as reps)",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 60, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 60, "is_warmup": false}
        ]
      },
      {
        "exercise": 18,
        "order_index": 7,
        "notes": "Standing calf raises",
        "sets": [
          {"set_index": 1, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 2, "weight_kg": 0, "reps": 8, "is_warmup": false},
          {"set_index": 3, "weight_kg": 0, "reps": 8, "is_warmup": false}
        ]
      }
    ]
  }'